ENVIRONMENT:
  MAX_EPISODE_STEPS: 513 # = 512 observations

SIMULATOR:
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  RGB_SENSOR:
    WIDTH: 342
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 342
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
  SEMANTIC_SENSOR:
    WIDTH: 342
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
    
TASK:
  TYPE: Exp-v0
  POSSIBLE_ACTIONS: ['MOVE_FORWARD', 'TURN_LEFT', 'TURN_RIGHT']
  SENSORS: ['POSE_SENSOR', 'COLLISION_SENSOR', 'WORLD_POSE_SENSOR']
  MEASUREMENTS: ['CELLS_COVERED', 'DISTANCE_TO_GOAL']
  REWARD_MEASURE: 'cells_covered'
  SUCCESS_MEASURE: 'cells_covered'

DATASET:
  TYPE: Exploration-v1
